Payment\DataAccessBundle\Entity\Expenses:
    type: entity
    repositoryClass: Payment\DataAccessBundle\Entity\ExpensesRepository
    table: expenses
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        transactionId:
            type: integer
            unsigned: false
            nullable: false
            column: transaction_id
        systemDate:
            type: datetime
            nullable: false
            column: system_date
        expenseDate:
            type: datetime
            nullable: false
            column: expense_date
        expenseValue:
            type: decimal
            nullable: false
            column: expense_value
        description:
            type: string
            length: 512
            fixed: false
            nullable: false
        expenseName:
            type: string
            length: 512
            fixed: false
            nullable: false
            column: expense_name
        expenseNumber:
            type: string
            length: 45
            fixed: false
            nullable: false
            column: expense_number
        expenseRuc:
            type: string
            length: 13
            fixed: false
            nullable: true
            column: expense_ruc
        expenseIva:
            type: decimal
            nullable: true
            column: expense_iva
        expenseAddress:
            type: string
            length: 512
            fixed: false
            nullable: true
            column: expense_address
        expensePhone:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: expense_phone
    lifecycleCallbacks: {  }
